"""init

Revision ID: 18a961432304
Revises: dd33cb03d01f
Create Date: 2022-04-21 18:16:45.606778

"""

# revision identifiers, used by Alembic.
revision = '18a961432304'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
