"""init

Revision ID: 638375a9f204
Revises: 9f90ae7a19ba
Create Date: 2022-04-22 13:49:34.665721

"""

# revision identifiers, used by Alembic.
revision = '638375a9f204'
down_revision = '9f90ae7a19ba'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
