"""init

Revision ID: 75bb81a9aa0a
Revises: 76b2272994a2
Create Date: 2022-04-22 13:46:38.897999

"""

# revision identifiers, used by Alembic.
revision = '75bb81a9aa0a'
down_revision = '76b2272994a2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
