"""init

Revision ID: 76b2272994a2
Revises: 18a961432304
Create Date: 2022-04-22 11:41:36.679914

"""

# revision identifiers, used by Alembic.
revision = '76b2272994a2'
down_revision = '18a961432304'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
