"""init

Revision ID: 9f90ae7a19ba
Revises: 75bb81a9aa0a
Create Date: 2022-04-22 13:48:12.813598

"""

# revision identifiers, used by Alembic.
revision = '9f90ae7a19ba'
down_revision = '75bb81a9aa0a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
