"""init

Revision ID: af22e4ec6209
Revises: ec28b5cd16c1
Create Date: 2022-04-22 13:59:27.273859

"""

# revision identifiers, used by Alembic.
revision = 'af22e4ec6209'
down_revision = 'ec28b5cd16c1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
