"""init

Revision ID: ec28b5cd16c1
Revises: 638375a9f204
Create Date: 2022-04-22 13:53:03.075714

"""

# revision identifiers, used by Alembic.
revision = 'ec28b5cd16c1'
down_revision = '638375a9f204'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
